language: php
php:
  - '5.6'
script:
  - phpunit travis-test.php --coverage-clover=coverage.xml
  - find / ! -readable -prune -o -name "coverage.xml" -print
after_success:
  - bash <(curl -s https://codecov.io/bash)
