language: php
php:
  - '5.6'
install:
  - composer require --dev phpunit/php-code-coverage
script:
  - phpunit travis-test.php --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
