language: php
sudo: enabled
php:
  - '5.6'
before_script:
  - pip install coverage
script:
  - phpunit travis-test.php --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
