language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
script:
  - vendor/bin/phpunit travis-test.php --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
