theme: jekyll-theme-modernist
title: LazyCurl <a href="https://travis-ci.org/lazycurl/lazycurl"><img src="https://travis-ci.org/lazycurl/lazycurl.svg?branch=master" alt="Build Status" /></a>
description: A PHP class which brings back @-prefix usage in CURL requests to live, even in PHP 7. <a href="http://lazycurl.net/">http://lazycurl.net/</a>
show_downloads: true
google_analytics: UA-101781275-1