name: workflow-test

on:
  push:
    branches: [ "master" ]
    paths:
      - '_lazycurl.php'
      - '_workflow-test.php'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Full coverage matrix from v5.3 to v8.4
        # php-version: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        php-version: ['7.4']

    services:
      # Lightweight background FTP server container for local access
      ftp:
        image: delfer/alpine-ftp-server:latest
        ports:
          - 21:21
          - 21001:21001
          - 21002:21002
          - 21003:21003
          - 21004:21004
          - 21005:21005
        env:
          USERS: "testuser|hrXVjPwMj8NuFkZW"
          ADDRESS: 127.0.0.1
          MIN_PORT: 21001
          MAX_PORT: 21015

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP v${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, fileinfo, openssl
          coverage: none

      - name: Execute Test
        run: php workflow-test.php
